site_name: pyml_bindgen -- OCaml-Python Bindings Generator
site_url: https://mooreryan.github.io/ocaml_python_bindgen/
repo_url: https://github.com/mooreryan/ocaml_python_bindgen
edit_uri: edit/main/_docs_src/src
site_description: Installation and usage instructions for pyml_bindgen, a program to generate OCaml bindings for Python classes via pyml.
site_author: Ryan M. Moore
nav:
  - pyml_bindgen: index.md
  - Examples & Tutorials:
    - Getting Started: getting-started.md
    - Lots of examples: examples.md
    - Matplotlib Example: matplotlib.md
    - Matplotlib Example 2: matplotlib-2.md
    - Handling Dictionaries: dictionaries.md
    - Handling Dictionaries 2: dictionaries-2.md
    - Recursive Classes: recursive.md
  - Rules:
    - Overview: rules-overview.md
    - Types: types.md
    - Function & Argument Names: names.md
    - Attributes & Properties: attributes.md
    - Instance Methods: instance-methods.md
    - Class & Static Methods; Functions: static-methods.md
  - Miscellaneous:
    - Auto-generating bindings: auto-gen-bindings.md
    - Attributes -- py_fun_name: ocaml-attributes.md
    - Converting `pyobjects` to OCaml types: of-pyobject.md
    - Embedding Python source: embedding-python.md
    - Handling Tuples: tuples.md
    - Gotchas & Known Bugs: gotchas-bugs.md
    - Splitting ml and mli files: split-ml-mli.md
theme:
  name: readthedocs
  custom_dir: custom_theme
  highlightjs: true
  hljs_languages:
    - ocaml
    - python
markdown_extensions:
  - meta
docs_dir: src
site_dir: ../_docs
