site_name: pyml_bindgen -- OCaml-Python Bindings Generator
site_url: https://mooreryan.github.io/ocaml_python_bindgen/
repo_url: https://github.com/mooreryan/ocaml_python_bindgen
edit_uri: edit/main/_docs_src/src
site_description: Installation and usage instructions for pyml_bindgen, a program to generate OCaml bindings for Python classes via pyml.
site_author: Ryan M. Moore
nav:
  - pyml_bindgen: index.md
  - Examples & Tutorials:
    - Getting Started: getting-started.md
    - Matplotlib Example: matplotlib.md
    - Matplotlib Example 2: matplotlib-2.md
  - Rules:
    - Types: types.md
    - Function & Argument Names: names.md
    - Attributes & Properties: attributes.md
    - Instance Methods: instance-methods.md
    - Class & Static Methods: static-methods.md
  - Miscellaneous:
    - Converting `pyobjects` to OCaml types: of-pyobject.md
    - Handling Tuples: tuples.md
    - Gotchas & Known Bugs: gotchas-bugs.md
theme:
  name: readthedocs
  custom_dir: custom_theme
  highlightjs: true
  hljs_languages:
    - ocaml
    - python
markdown_extensions:
  - meta
docs_dir: src
site_dir: ../_docs
