name: Build and test

on:
  push:
    branches:
      - "main"
      - "staging"
      - "dev"

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.0
          - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          cache-prefix: v1-${{ matrix.os }}
          opam-local-packages: pyml_bindgen.opam

      - run: opam install ./pyml_bindgen.opam --deps-only --with-doc --with-test

      - name: Check release profile
        run: |
          opam exec -- make clean
          opam exec -- make build_release
          opam exec -- make test_release
          opam exec -- make install_release

      - name: Check dev profile
        run: |
          opam install ./pyml_bindgen-dev.opam --deps-only --with-doc --with-test
          opam exec -- make clean
          opam exec -- make build_dev
          opam exec -- make test_dev
          opam exec -- make install_dev
        if: matrix.ocaml-compiler == '4.14.0'

      # Send the coverage.
      - name: Send coverage
        run: |
          opam install bisect_ppx
          opam exec -- make send_coverage
        if: matrix.ocaml-compiler == '4.14.0'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
